### PR TITLE
Add option to allow invalid hosts for ssl certs

### LINKED ISSUE #7: SSL CN validace
Od  PHP 5.6 je v php defaultne zapla validace common name u SSL.

Nektere certifikaty cloudovych sluzeb proto nemusi fungovat, protoze nemaji CN shodne s hostname:
https://bugs.php.net/bug.php?id=71845

Toto nastaveni se neda pro soucasnou verzi PDO vypnout.

Pro klienty, kteri nemaji moznost vygenerovat spravny SSL certifikat je k dispozici MySQL ex postaveny nad PHP5.5.9
https://github.com/keboola/db-extractor-mysql-php55

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #7

### CODE REVIEW

**Comment by ujovlado** [comment]
I would vote for something like `sslNoVerify`, what do you think?

**Comment by ujovlado** [comment]
But it's under `ssl` already, so `noVerifyServerCert` would be even better.

**Comment by pivnicek** [comment]
yeha, I struggled with the name:).  How about `verifyServerCert` default true?  I don't like having the negation in the name

**Comment by ujovlado** [comment]
Ok, than. Makes also sense from UI point of view, when we add checkbox like this (default checked):

- [x] Verify server certificate

**Comment by ujovlado** [comment]
One update pls, rename also that test fn :)

**Pull request merged**
