### PR TITLE
Update dependency

### LINKED ISSUE #59: Application error on test connection
```
 Failed to connect!
Contact support@keboola.com and attach this exception id. docker-3ddc9cc9ddeb5d30e5198f0d81729221
```

### PR DESCRIPTION
**Pull request by Actimel**
Fixes #59

### CODE REVIEW

**Comment by pivnicek** [comment]
hmm, but this passes https://github.com/keboola/db-extractor-mysql/pull/61/commits/ce1853b1bd0392d5c720500c7a599ea71115b555#diff-ab9f40623aa884f81bddd80e0dcd52d4L19

**Comment by Actimel** [comment]
That's false positive
```
ds@DS-MacBook-Pro:~/projects/keboola/db-extractor-mysql (david-update-db-extractor-common)$ docker-compose run --rm dev /bin/bash
Starting db-extractor-mysql_mysql_1 ... done
Starting db-extractor-mysql_sshproxy_1 ... done
root@56bfe97ad7c0:/code# php src/run.php --data=/code/data
The child node "outputTable" at path "parameters" must be configured.
```

**Comment by pivnicek** [comment]
ok, just a second, I'll update

**Comment by Actimel** [comment]
We need to revert that require or make those ConfigDefinitions like in db-extractor-common.

**Comment by Actimel** [comment]
Now it's good 👍

**Pull request merged**
