### PR TITLE
fix gettables with no column

### PR DESCRIPTION
**Pull request by ondrajodas**
fixes - https://keboola.slack.com/archives/C035LGNK5/p1578309422000400

### CODE REVIEW

**Comment by ondrajodas** [comment]
no problém je v tom že nevím jak to nasimulovat -> jak vytvořit tabulku která nemá žádný sloupec?

**Comment by pivnicek** [comment]
`CREATE TABLE `no-columns-table`;` :-)

**Comment by ondrajodas** [comment]
`A table must have at least 1 column`

**Comment by pivnicek** [comment]
hmmm,  I will try something

**Comment by pivnicek** [comment]
ugh, I haven't got it.  I wonder what the table that triggered this exception looks like.  I'll ask on the ticket.

**Comment by pivnicek** [comment]
ok, I think it must be a special object like an global index or something, but I haven't been able to get it.  regardless I'm quite sure your change is ok.

**Comment by ondrajodas** [comment]
i just update `db-extractor-table-format`

**Pull request merged**
